---
run_mode: prod_debug
ban_prefix_size: 2
max_attempts: 3
check_interval: 10
log_refused: true
mail:
    server: smtp.gmail.com
    port: 587
    sender: surveyor@home
    recipient: xxx
    passwd: xxx
    active: false
